# Generated by Django 4.1 on 2022-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_quiz_is_active_alter_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, upload_to="Images"),
        ),
    ]
