# Generated by Django 4.1 on 2022-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quiz_passed_members_alter_question_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passed_members',
            field=models.FloatField(default=0),
        ),
    ]
