# Generated by Django 4.1 on 2022-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quiz_passed_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passed_members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
