# Generated by Django 4.1 on 2022-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quiz_passed_members_delete_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passed_members',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
