# Generated by Django 4.1 on 2022-08-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answered_questions',
            field=models.JSONField(default=None),
        ),
    ]
