# Generated by Django 4.1 on 2022-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed_tests',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quizz_and_ans',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='answered_questions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
