# Generated by Django 4.1 on 2022-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_passed_tests_user_quizz_and_ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
