# Generated by Django 4.1 on 2022-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local_rank',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
