# Generated by Django 4.1 on 2022-08-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_local_rank_alter_user_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Таблица лидеров',
                'verbose_name_plural': 'Таблица лидеров',
            },
            bases=('user.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='local_rank',
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
