# Generated by Django 4.1 on 2022-08-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_leaderboard_remove_user_local_rank_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='users',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blabla', to=settings.AUTH_USER_MODEL),
        ),
    ]
