# Generated by Django 4.1 on 2022-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0013_leaderboard_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.group'),
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
            ],
            options={
                'verbose_name': 'Таблица лидеров',
                'verbose_name_plural': 'Таблица лидеров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
